source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'
workspace 'WLTCocktail'
use_frameworks!

target 'WLTCocktail' do
  project 'WLTCocktail/WLTCocktail'

  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for WLTCocktail
  pod 'SwiftLint' #used for linting
  pod 'Cache' #used for caching api responses
  
  target 'WLTCocktailTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WLTCocktailUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']
      cflags << '-fembed-bitcode'
      config.build_settings['OTHER_CFLAGS'] = cflags
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings.delete 'IOS_DEPLOYMENT_TARGET'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
    end
  end
end
